/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import model.Address;
import model.Contact;
import model.person;

/**
 *
 * @author balin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private person person;
    public NewJFrame() {
        initComponents();
        this.person= new person();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Creatjpanel = new javax.swing.JPanel();
        Firstnamefield = new javax.swing.JTextField();
        Currentstreetfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NUIDfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Lastnamefield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Collegenamefield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Officephonefield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Officeemailfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Personalphonefield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Personalemailfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Currentaptfield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Currentcityfield = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Currentzipfield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Permstreetfield = new javax.swing.JTextField();
        Permaptfield = new javax.swing.JTextField();
        Permcityfield = new javax.swing.JTextField();
        Permzipfield = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Viewjpanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Viewfirstname = new javax.swing.JLabel();
        Viewcurrentstreet = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Viewcollegename = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Viewnuid = new javax.swing.JTextField();
        Viewlastname = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Viewofficephone = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Viewofficeemail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Viewpersonalphone = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Viewpersonalemail = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Viewcurrentapt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Viewcurrentzip = new javax.swing.JTextField();
        Viewcurrentcity = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Viewpermstreet = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Viewpermapt = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        Viewpermcity = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        Viewpermzip = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(204, 204, 255));
        jSplitPane1.setForeground(new java.awt.Color(204, 204, 255));

        Creatjpanel.setBackground(new java.awt.Color(204, 204, 255));
        Creatjpanel.setForeground(new java.awt.Color(204, 204, 255));

        Firstnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnamefieldActionPerformed(evt);
            }
        });

        Currentstreetfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentstreetfieldActionPerformed(evt);
            }
        });

        jLabel2.setText("First Name");

        jLabel3.setText("Current Street Name");

        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("NUID");

        jLabel5.setText("Last Name");

        Lastnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnamefieldActionPerformed(evt);
            }
        });

        jLabel6.setText("College Name");

        Collegenamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollegenamefieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Office Phone");

        Officephonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfficephonefieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Office email_id");

        Officeemailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfficeemailfieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Personal Phone");

        Personalphonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalphonefieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Personal email_id");

        Personalemailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalemailfieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Current Address");

        jLabel12.setText("Current Apt No.");

        Currentaptfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentaptfieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Current City/State");

        Currentcityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentcityfieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Current Zipcode");

        jLabel15.setText("Permanent Street Name");

        jLabel16.setText("Permanent Apt No.");

        jLabel17.setText("Permanent City/State");

        jLabel18.setText("Permanent Zipcode");

        Permaptfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermaptfieldActionPerformed(evt);
            }
        });

        Permcityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermcityfieldActionPerformed(evt);
            }
        });

        jLabel19.setText("Permanent Address");

        javax.swing.GroupLayout CreatjpanelLayout = new javax.swing.GroupLayout(Creatjpanel);
        Creatjpanel.setLayout(CreatjpanelLayout);
        CreatjpanelLayout.setHorizontalGroup(
            CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatjpanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(CreatjpanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Currentstreetfield, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CreatjpanelLayout.createSequentialGroup()
                            .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(64, 64, 64)
                            .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Firstnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addComponent(Collegenamefield)
                                .addComponent(Officephonefield)
                                .addComponent(Personalphonefield))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreatjpanelLayout.createSequentialGroup()
                        .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Currentaptfield)
                            .addComponent(Currentcityfield)
                            .addComponent(Currentzipfield))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatjpanelLayout.createSequentialGroup()
                        .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreatjpanelLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreatjpanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(NUIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatjpanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Officeemailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatjpanelLayout.createSequentialGroup()
                        .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreatjpanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(Personalemailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreatjpanelLayout.createSequentialGroup()
                                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(27, 27, 27)
                                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Permstreetfield, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(Permaptfield)
                                    .addComponent(Permcityfield)
                                    .addComponent(Permzipfield))))
                        .addGap(48, 48, 48))))
            .addGroup(CreatjpanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatjpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatjpanelLayout.createSequentialGroup()
                        .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatjpanelLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        CreatjpanelLayout.setVerticalGroup(
            CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatjpanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Firstnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Collegenamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Officephonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Officeemailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(27, 27, 27)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Personalphonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Personalemailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(26, 26, 26)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19))
                .addGap(29, 29, 29)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Currentstreetfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(Permstreetfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Currentaptfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(Permaptfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Currentcityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(Permcityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(CreatjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Currentzipfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(Permzipfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(savebutton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(Creatjpanel);

        Viewjpanel.setBackground(new java.awt.Color(0, 255, 255));
        Viewjpanel.setForeground(new java.awt.Color(0, 255, 255));

        name.setText("First Name");

        jLabel4.setText("Current Street Name");

        Viewcurrentstreet.setText("jLabel5");

        jLabel20.setText("College Name");

        Viewcollegename.setText("jTextField1");

        jLabel21.setText("Last Name");

        jLabel22.setText("NUID");

        Viewnuid.setText("jTextField2");

        Viewlastname.setText("jTextField3");

        jLabel23.setText("Office Phone");

        Viewofficephone.setText("jTextField4");

        jLabel24.setText("Office email id");

        Viewofficeemail.setText("jTextField5");

        jLabel25.setText("Personal Phone");

        Viewpersonalphone.setText("jTextField6");

        jLabel26.setText("Perosnal email");

        Viewpersonalemail.setText("jTextField7");

        jLabel27.setText("Current Apt No.");

        Viewcurrentapt.setText("jTextField8");

        jLabel28.setText("CUrrent CIty/State");

        jLabel29.setText("Current Zipcode");

        Viewcurrentzip.setText("jTextField9");

        Viewcurrentcity.setText("jTextField10");
        Viewcurrentcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewcurrentcityActionPerformed(evt);
            }
        });

        jLabel30.setText("Permanent Street Name");

        Viewpermstreet.setText("jTextField11");

        jLabel31.setText("Permanent Apt No.");

        Viewpermapt.setText("jTextField12");

        jLabel32.setText("Permanent City/State");

        Viewpermcity.setText("jTextField13");

        jLabel33.setText("Permanent Zipcode");

        Viewpermzip.setText("jTextField14");

        jLabel34.setText("Current Address ");

        jLabel35.setText("Permanent Address");

        javax.swing.GroupLayout ViewjpanelLayout = new javax.swing.GroupLayout(Viewjpanel);
        Viewjpanel.setLayout(ViewjpanelLayout);
        ViewjpanelLayout.setHorizontalGroup(
            ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewjpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ViewjpanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Viewcurrentcity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewjpanelLayout.createSequentialGroup()
                        .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Viewfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Viewcollegename, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Viewofficephone, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Viewpersonalphone, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Viewcurrentstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Viewcurrentapt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Viewcurrentzip, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(ViewjpanelLayout.createSequentialGroup()
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Viewlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ViewjpanelLayout.createSequentialGroup()
                                    .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Viewofficeemail, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Viewnuid, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Viewpersonalemail, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Viewpermstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Viewpermapt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Viewpermcity, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Viewpermzip, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(ViewjpanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewjpanelLayout.setVerticalGroup(
            ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewjpanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(Viewfirstname)
                    .addComponent(jLabel21)
                    .addComponent(Viewlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Viewcollegename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(Viewnuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Viewofficephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(Viewofficeemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Viewpersonalphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(Viewpersonalemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Viewcurrentstreet)
                    .addComponent(jLabel30)
                    .addComponent(Viewpermstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Viewcurrentapt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(Viewpermapt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ViewjpanelLayout.createSequentialGroup()
                        .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(Viewcurrentcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(Viewpermcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewjpanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel29))
                            .addGroup(ViewjpanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(ViewjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel33)
                                    .addComponent(Viewpermzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(Viewcurrentzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(Viewjpanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnamefieldActionPerformed

    private void CurrentstreetfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentstreetfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentstreetfieldActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
       String FirstName= Firstnamefield.getText();
       String LastName= Lastnamefield.getText();
       String CollegeName= Collegenamefield.getText();
       String NUID=NUIDfield.getText();
       
       String Officephone=Officephonefield.getText();
       String Officeemail=Officeemailfield.getText();
       String Personalphone=Personalphonefield.getText();
       String Personalemail=Personalemailfield.getText();
      // String Currentstreetname=Currentstreetfield.getText();
      
       String Currentaptno=Currentaptfield.getText();
       String Currentcity= Currentcityfield.getText();
       String Currentzip= Currentzipfield.getText();
       
       String Permstreetname=Permstreetfield.getText();
       String Permaptno=Permaptfield.getText();
       String Permcity=Permcityfield.getText();
       String Permzip=Permzipfield.getText();
       String Currentstreetname=Currentstreetfield.getText();
       
        this.person.setfirstName(FirstName);
        this.person.setlastname(LastName);
        this.person.setNUID(NUID);
        this.person.setcollegename(CollegeName);
        
        
               // person obj2=new person();
        Address address=this.person.getAddress();
        address.setCurrentstreetname(Currentstreetname);
        address.setCurrentaptno(Currentaptno);
        address.setCurrentcity(Currentcity);
        address.setCurrentzip(Currentzip) ;
        
        address.setPermstreetname(Permstreetname);
        address.setPermaptno(Permaptno);
        address.setPermcity(Permcity);
        address.setPermzip(Permzip);
        
        Contact contact=this.person.getContact();
        contact.setOfficephone(Officephone);
        contact.setOfficeemail(Officeemail);
        contact.setPersonalphone(Personalphone);
        contact.setPersonalemail(Personalemail);
        
        display();
        
    }//GEN-LAST:event_savebuttonActionPerformed

    private void LastnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnamefieldActionPerformed

    private void CollegenamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollegenamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CollegenamefieldActionPerformed

    private void OfficephonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfficephonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OfficephonefieldActionPerformed

    private void OfficeemailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfficeemailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OfficeemailfieldActionPerformed

    private void PersonalphonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalphonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonalphonefieldActionPerformed

    private void PersonalemailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalemailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonalemailfieldActionPerformed

    private void CurrentaptfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentaptfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentaptfieldActionPerformed

    private void CurrentcityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentcityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentcityfieldActionPerformed

    private void PermaptfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermaptfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermaptfieldActionPerformed

    private void PermcityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermcityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermcityfieldActionPerformed

    private void ViewcurrentcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewcurrentcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewcurrentcityActionPerformed
private void display(){
    Viewfirstname.setText(this.person.getfirstName());
    Viewlastname.setText(this.person.getlastname());
    Viewcollegename.setText(this.person.getcollegename());
    Viewnuid.setText(this.person.getNUID());
    
//    Viewcurrentstreet.setText(this.person.getAddress().)
    Viewcurrentstreet.setText(this.person.getAddress().getCurrentstreetname());
    Viewcurrentapt.setText(this.person.getAddress().getCurrentaptno());
    Viewcurrentcity.setText(this.person.getAddress().getCurrentcity());
    Viewcurrentzip.setText(this.person.getAddress().getCurrentzip());
    
    Viewpermstreet.setText(this.person.getAddress().getPermstreetname());
    Viewpermapt.setText(this.person.getAddress().getPermaptno().toString());
    Viewpermcity.setText(this.person.getAddress().getPermcity());
    Viewpermzip.setText(this.person.getAddress().getPermzip());
    
    Viewofficephone.setText(this.person.getContact().getOfficephone().toString());
   Viewofficeemail.setText(this.person.getContact().getOfficeemail());
   Viewpersonalphone.setText(this.person.getContact().getPersonalphone());
   Viewpersonalemail.setText(this.person.getContact().getPersonalemail());
    
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Collegenamefield;
    private javax.swing.JPanel Creatjpanel;
    private javax.swing.JTextField Currentaptfield;
    private javax.swing.JTextField Currentcityfield;
    private javax.swing.JTextField Currentstreetfield;
    private javax.swing.JTextField Currentzipfield;
    private javax.swing.JTextField Firstnamefield;
    private javax.swing.JTextField Lastnamefield;
    private javax.swing.JTextField NUIDfield;
    private javax.swing.JTextField Officeemailfield;
    private javax.swing.JTextField Officephonefield;
    private javax.swing.JTextField Permaptfield;
    private javax.swing.JTextField Permcityfield;
    private javax.swing.JTextField Permstreetfield;
    private javax.swing.JTextField Permzipfield;
    private javax.swing.JTextField Personalemailfield;
    private javax.swing.JTextField Personalphonefield;
    private javax.swing.JTextField Viewcollegename;
    private javax.swing.JTextField Viewcurrentapt;
    private javax.swing.JTextField Viewcurrentcity;
    private javax.swing.JLabel Viewcurrentstreet;
    private javax.swing.JTextField Viewcurrentzip;
    private javax.swing.JLabel Viewfirstname;
    private javax.swing.JPanel Viewjpanel;
    private javax.swing.JTextField Viewlastname;
    private javax.swing.JTextField Viewnuid;
    private javax.swing.JTextField Viewofficeemail;
    private javax.swing.JTextField Viewofficephone;
    private javax.swing.JTextField Viewpermapt;
    private javax.swing.JTextField Viewpermcity;
    private javax.swing.JTextField Viewpermstreet;
    private javax.swing.JTextField Viewpermzip;
    private javax.swing.JTextField Viewpersonalemail;
    private javax.swing.JTextField Viewpersonalphone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel name;
    private javax.swing.JButton savebutton;
    // End of variables declaration//GEN-END:variables
}
