/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Application;

/**
 *
 * @author balin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Application application;
    public MainJFrame() {
        initComponents();
        this.application = new Application();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        assignButton = new javax.swing.JButton();
        creatObservationButton = new javax.swing.JButton();
        vitalSignButton = new javax.swing.JButton();
        medicineCatalogButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlJPanel.setBackground(new java.awt.Color(255, 204, 204));
        controlJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignButton.setText("ASSIGN MEDICINE");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(assignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 40));

        creatObservationButton.setText("CREATE OBSERVATION");
        creatObservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatObservationButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(creatObservationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 30));

        vitalSignButton.setText("VIEW VITAL SIGN HISTORY");
        vitalSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalSignButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(vitalSignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 30));

        medicineCatalogButton.setText("MEDICINE CATALOG");
        medicineCatalogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineCatalogButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(medicineCatalogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 30));

        jSplitPane1.setLeftComponent(controlJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        // TODO add your handling code here:
        
         jSplitPane1.setRightComponent(new MedicineAssignJPanel(this.application));
    }//GEN-LAST:event_assignButtonActionPerformed

    private void creatObservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatObservationButtonActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CreateJPanel(this.application));
    }//GEN-LAST:event_creatObservationButtonActionPerformed

    private void vitalSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalSignButtonActionPerformed
        // TODO add your handling code here:
        
           jSplitPane1.setRightComponent(new ViewJPanel(this.application));
    }//GEN-LAST:event_vitalSignButtonActionPerformed

    private void medicineCatalogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineCatalogButtonActionPerformed
        // TODO add your handling code here:
           
             jSplitPane1.setRightComponent(new CatalogJPanel(this.application));
    }//GEN-LAST:event_medicineCatalogButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignButton;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JButton creatObservationButton;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton medicineCatalogButton;
    private javax.swing.JButton vitalSignButton;
    // End of variables declaration//GEN-END:variables
}
